on: 
  # schedule:
  # - cron: "* */8 * * *"
  push:
    branches:
    # - master
    - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: write config
        run: |
          echo "$CONFIG_FILE" > ./config/config.json
        shell: bash
        env:
          CONFIG_FILE: ${{secrets.CONFIG_FILE}}

      - name: test
        run: go run . -run -noduplicate -nomail
